const fs = require('fs');
const path = require('path');

function parseAttributes(tagText) {
  const attrs = {};
  const re = /(\w+)="([^"]*)"/g;
  let m;
  while ((m = re.exec(tagText)) !== null) {
    attrs[m[1]] = m[2];
  }
  return attrs;
}

function toNum(value, fallback) {
  if (value === undefined || value === null || value === '') return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function formatNum(n) {
  if (!Number.isFinite(n)) return '0';
  const s = (Math.round(n * 1000) / 1000).toString();
  return s;
}

function formatLuaString(s) {
  return `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function buildTexMappings(scml) {
  const fileById = new Map();
  const texlibEntries = new Map();

  const folderMatch = scml.match(/<folder\b[\s\S]*?<\/folder>/);
  if (!folderMatch) return { fileById, texlibEntries };

  const folderBody = folderMatch[0];
  const fileRe = /<file\b([^>]*)\/>/g;
  let fm;
  while ((fm = fileRe.exec(folderBody)) !== null) {
    const attrs = parseAttributes(fm[1]);
    const fileId = attrs.id;
    const fileName = attrs.name || '';
    const base = path.basename(fileName, path.extname(fileName));

    let tex = `${base}.tex`;
    let texKey = null;
    const cloudNum = base.match(/^cloud-(\d+)$/);
    if (cloudNum) {
      texKey = `c${cloudNum[1]}`;
      texlibEntries.set(texKey, tex);
    }

    fileById.set(String(fileId), {
      tex,
      texKey,
      base,
    });
  }

  return { fileById, texlibEntries };
}

function parseMainlineOrder(animationBody) {
  const result = new Map();
  const mainlineMatch = animationBody.match(/<mainline>([\s\S]*?)<\/mainline>/);
  if (!mainlineMatch) return result;

  const firstKeyMatch = mainlineMatch[1].match(/<key\b[^>]*>([\s\S]*?)<\/key>/);
  if (!firstKeyMatch) return result;

  const refsBlock = firstKeyMatch[1];
  const refRe = /<object_ref\b([^>]*)\/>/g;
  let rm;
  while ((rm = refRe.exec(refsBlock)) !== null) {
    const attrs = parseAttributes(rm[1]);
    const timelineId = String(attrs.timeline);
    const zIndex = toNum(attrs.z_index, 0);
    result.set(timelineId, {
      zIndex,
      mainlineName: attrs.name || null,
    });
  }

  return result;
}

function parseTimeline(timelineBody, timelineAttrs, fileById) {
  const timelineId = String(timelineAttrs.id);
  const timelineName = timelineAttrs.name || `timeline_${timelineId}`;

  const keyframes = [];
  let texRef = null;

  const keyRe = /<key\b([^>]*)>([\s\S]*?)<\/key>/g;
  let km;
  while ((km = keyRe.exec(timelineBody)) !== null) {
    const keyAttrs = parseAttributes(km[1]);
    const keyBody = km[2];

    const timeMs = toNum(keyAttrs.time, 0);
    const t = timeMs / 1000;

    const objMatch = keyBody.match(/<object\b([^>]*)\/>/);
    if (!objMatch) continue;
    const objAttrs = parseAttributes(objMatch[1]);

    const fileId = String(objAttrs.file);
    const fileInfo = fileById.get(fileId);
    if (!fileInfo) continue;

    if (!texRef) texRef = fileInfo.texKey || fileInfo.tex;

    keyframes.push({
      t,
      x: toNum(objAttrs.x, 0),
      y: toNum(objAttrs.y, 0),
      sx: toNum(objAttrs.scale_x, 1),
      sy: toNum(objAttrs.scale_y, 1),
      rot: toNum(objAttrs.angle, 0),
      a: toNum(objAttrs.a, 1),
    });
  }

  return {
    id: timelineName,
    timelineId,
    tex: texRef,
    keyframes,
  };
}

function parseAnimations(scml, fileById) {
  const animationMap = new Map([
    ['cloud_in', 'in'],
    ['cloud_idle', 'idle'],
    ['cloud_out', 'out'],
  ]);

  const parsed = {
    in: [],
    idle: [],
    out: [],
  };

  const animRe = /<animation\b([^>]*)>([\s\S]*?)<\/animation>/g;
  let am;
  while ((am = animRe.exec(scml)) !== null) {
    const animAttrs = parseAttributes(am[1]);
    const rawName = animAttrs.name;
    const animName = animationMap.get(rawName);
    if (!animName) continue;

    const animBody = am[2];
    const orderMap = parseMainlineOrder(animBody);

    const timelines = [];
    const tlRe = /<timeline\b([^>]*)>([\s\S]*?)<\/timeline>/g;
    let tm;
    while ((tm = tlRe.exec(animBody)) !== null) {
      const tlAttrs = parseAttributes(tm[1]);
      const tlData = parseTimeline(tm[2], tlAttrs, fileById);
      if (!tlData.tex || tlData.keyframes.length === 0) continue;

      const order = orderMap.get(String(tlAttrs.id));
      tlData.zIndex = order ? order.zIndex : 9999;
      timelines.push(tlData);
    }

    timelines.sort((a, b) => {
      if (a.zIndex !== b.zIndex) return a.zIndex - b.zIndex;
      return a.id.localeCompare(b.id);
    });

    parsed[animName] = timelines;
  }

  return parsed;
}

function emitLuaConfig(texlibEntries, anims, atlas) {
  const lines = [];

  lines.push('-- generated by tools/convert_mist_scml.js');
  lines.push('return {');
  lines.push(`  atlas = ${formatLuaString(atlas)},`);
  lines.push('  frame_step = 1 / 30,');
  lines.push('texlib = {');
  const texKeys = Array.from(texlibEntries.keys()).sort((a, b) => a.localeCompare(b));
  for (const k of texKeys) {
    lines.push(`  ${k} = ${formatLuaString(texlibEntries.get(k))},`);
  }
  lines.push('},');
  lines.push('anims = {');

  for (const animName of ['in', 'idle', 'out']) {
    const loop = animName === 'idle' ? 'true' : 'false';
    const elements = anims[animName] || [];
    lines.push(`  ['${animName}'] = {`);
    lines.push(`    loop = ${loop},`);
    lines.push('    elements = {');

    for (const el of elements) {
      lines.push('      {');
      lines.push(`        id = ${formatLuaString(el.id)},`);
      lines.push(`        tex = ${formatLuaString(el.tex)},`);
      lines.push('        keyframes = {');
      for (const kf of el.keyframes) {
        lines.push(
          `          { t = ${formatNum(kf.t)}, x = ${formatNum(kf.x)}, y = ${formatNum(kf.y)}, sx = ${formatNum(kf.sx)}, sy = ${formatNum(kf.sy)}, rot = ${formatNum(kf.rot)}, a = ${formatNum(kf.a)} },`
        );
      }
      lines.push('        },');
      lines.push('      },');
    }

    lines.push('    },');
    lines.push('  },');
  }

  lines.push('},');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function main() {
  const repoRoot = process.cwd();
  const input = process.argv[2] || path.join(repoRoot, 'ling_cloud_pavilion_mist.scml');
  const output = process.argv[3] || path.join(repoRoot, 'scripts', 'widgets', 'config', 'ling_cloud_pavilion_mist_anim.lua');

  const scml = fs.readFileSync(input, 'utf8');
  const { fileById, texlibEntries } = buildTexMappings(scml);
  const anims = parseAnimations(scml, fileById);
  const lua = emitLuaConfig(texlibEntries, anims, 'images/ling_cloud_pavilion_mist.xml');

  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, lua, 'utf8');

  console.log('Generated:', output);
  console.log('Elements count:', {
    in: anims.in.length,
    idle: anims.idle.length,
    out: anims.out.length,
  });
}

main();
